#!/bin/sh
# The goal of this script is to allow mapping of host user (the one running
# docker), to the desired container user, as to enable the use of more
# restrictive file permission (700 or 600)

# does a group with name = EGROUP already exist ?
EXISTING_GID=$( getent group $EGROUP | cut -f3 -d ':' )

if [ ! -z $EXISTING_GID ]; then
   if [ $EXISTING_GID != $EGID ]; then
      # change id of the existing group
      groupmod -g $EGID $EGROUP
   fi
else
   # create new group with id = EGID
   addgroup -g $EGID $EGROUP
fi

# does a user with name = EUSER already exist ?
EXISTING_UID=$( getent passwd $EUSER | cut -f3 -d ':' )

if [ ! -z $EXISTING_UID ]; then
   if [ $EXISTING_UID != $EUID ]; then
      if [ ! -z $EHOME ]; then
         if [ $ENOLOGIN = "yes" ]; then 
            # change login, home, shell (nologin) and primary group of the existing user
            usermod -s /sbin/nologin -u $EUID -g $EGROUP -d $EHOME $EUSER
         else
            # change login, home, and primary group of the existing user
            usermod -s /bin/sh -u $EUID -g $EGROUP -d $EHOME $EUSER
         if
      else
         if [ $ENOLOGIN = "yes" ]; then 
            # change login, shell (nologin) and primary group of the existing user
            usermod -s /sbin/nologin -u $EUID -g $EGROUP $EUSER
         else
            # change login and primary group of the existing user
            usermod -s /bin/sh -u $EUID -g $EGROUP $EUSER
         fi
      fi
   fi
else
   if [ ! -z $EHOME ]; then
      if [ $ENOLOGIN = "yes" ]; then 
         # create new user with id = EUID, group = EGROUP and home directory = EHOME,
         # with nologin shell
         adduser -s /sbin/nologin -u $EUID -G $EGROUP -h $EHOME -D $EUSER
      else
         # create new user with id = EUID, group = EGROUP and home directory = EHOME,
         # with default shell
         adduser -s /bin/sh -u $EUID -G $EGROUP -h $EHOME -D $EUSER
      fi
   else
      if [ $ENOLOGIN = "yes" ]; then 
         # create new user with id = EUID and group = EGROUP, with nologin shell
         adduser -s /sbin/nologin -u $EUID -G $EGROUP -D $EUSER
      else
         # create new user with id = EUID and group = EGROUP, with default shell
         adduser -s /bin/sh -u $EUID -G $EGROUP -D $EUSER
      fi
   fi
fi

if [ ! -z $EHOME ]; then
   if [ $ECHOWNHOME = "yes" ]; then 
      # change ownership of home directory
      chown $EUSER:$EGROUP $EHOME
   fi
fi
